import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/ui/themes";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      afterSignOutUrl={
        process.env.NEXT_PUBLIC_CLERK_SIGN_IN_URL ?? "/sign-in"
      }
      signInFallbackRedirectUrl="/editor"
      signUpFallbackRedirectUrl="/editor"
      appearance={{
        theme: dark,
        variables: {
          colorPrimary: "var(--accent-primary)",
          colorPrimaryForeground: "var(--bg-base)",
          colorDanger: "var(--state-error)",
          colorSuccess: "var(--state-success)",
          colorWarning: "var(--state-warning)",
          colorForeground: "var(--text-primary)",
          colorMuted: "var(--bg-subtle)",
          colorMutedForeground: "var(--text-muted)",
          colorBackground: "var(--bg-elevated)",
          colorInputForeground: "var(--text-primary)",
          colorInput: "var(--bg-subtle)",
          colorRing: "var(--accent-primary)",
          colorBorder: "var(--border-default)",
          fontFamily: "var(--font-geist-sans)",
          fontFamilyMono: "var(--font-geist-mono)",
          borderRadius: "var(--radius)",
        },
      }}
    >
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} dark h-full antialiased`}
      >
        <body
          suppressHydrationWarning
          className="min-h-full flex flex-col"
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
